[config]
reload_apps = true

[templates.waybar-docked]
input_path = '~/.config/matugen/templates/waybar-docked.css'
output_path = '~/.config/waybar/style-docked.css'

[templates.waybar-floating]
input_path = '~/.config/matugen/templates/waybar-floating.css'
output_path = '~/.config/waybar/style-floating.css'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.mako]
input_path = '~/.config/matugen/templates/mako-colors'
output_path = '~/.config/mako/config'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'


[templates.fastfetch]
input_path = '~/.config/matugen/templates/fastfetch.jsonc'
output_path = '~/.config/fastfetch/config.jsonc'

[templates.helium]
input_path = '~/.config/matugen/templates/helium-theme.json'
output_path = '~/.config/matugen/helium-dynamic-theme/manifest.json'

[templates.wofi]
input_path = '~/.config/matugen/templates/wofi.css'
output_path = '~/.config/wofi/style.css'

