general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 600
    on-timeout = /usr/bin/hyprlock
}

# 90 seconds — turn off display
listener {
    timeout = 700
    on-timeout = /usr/bin/hyprctl dispatch dpms off
    on-resume = /usr/bin/hyprctl dispatch dpms on
}
