hl.on("hyprland.start", function()
    hl.exec_cmd("sleep 2")
	hl.exec_cmd("awww-daemon")
    hl.exec_cmd("systemctl --user enable --now hyprpolkitagent")
    hl.exec_cmd("mako")
    --hl.exec_cmd("nohup waybar -c ~/.config/waybar/config-floating.jsonc -s ~/.config/waybar/style-floating.css > /dev/null 2>&1 &")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("systemctl --user enable --now hyprpolkitagent.service")
    hl.exec_cmd("warp-cli connect && warp-taskbar")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("hypridle")
end)

